spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SHIPPING_EMAIL}
spring.mail.password=${PASSWORD_EMAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
